#!/bin/bash

# Check if the number of command line arguments is less than 1
if [ $# -lt 1 ]; then
  echo "Usage: $0 <file_path> <url> [install] [test] [dev]"
  exit 1
fi

# Obtain command line argument
arg=$1
# echo "Argument: $arg";

# Install dependencies
if [ "$arg" == "install" ]; then
  npm install
  exit 0
fi

# Run the test suite
if [ "$arg" == "test" ]; then
  npm run auto-grader-test | grep -v "JSON report written to"
  npm run build
  node dist/utils/reports/extract-results.js
  exit 0
fi

# Check if the argument is a file path
if [ -f "$arg" ]; then
  # Compile TS files && Vite build
  cd client
  npm run build
  # Copy the "build" folder to "/var/www/html" for Nginx
  sudo cp -R build/ /var/www/html/front-end/
  # Compile TS files
  cd ../backend
  npm run build
  # Start Server
  npm run start
  exit 0
fi

exit 1
