#  Author(s): Geromy Cunningham
#  Purpose: continuous integration pipeline for the Trustworthy Module Registry project. Builds and tests the backend and frontend of the project. Runs security checks on the project.
---
name: CI/CD Pipeline

on:
  push:
    branches-ignore: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        id: setup-node-be
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install and Build Backend
        run: |
          npm install
          npm run build --if-present
          npm test
        working-directory: ./backend

      - name: Setup Node.js ${{ matrix.node-version }}
        id: setup-node-fe
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install and Build Client
        run: |
          npm install
          npm run build --if-present
          npm test
        working-directory: ./client

      - name: Run Security Checks
        run: npm audit
