name: CI/CD Pipeline
on:
  push:
    branches-ignore: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: |
          npm install --save-dev @types/jest @types/testing-library__jest-dom --workspace=frontend
          npm install
          npm run build --if-present
          npm test

      - name: Run Security Checks
        run: npm audit
#   continuous-deployment:
#     runs-on: ubuntu-latest
#     needs: continuous-integration
#     if: github.ref == 'refs/heads/main'

#     steps:
#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v2
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1

#       - name: Deploy to S3
#         run: |
#           aws s3 sync ./ s3://codepipeline-us-east-1-989702721762
