# This workflow executes several linters on changed files based on languages
# used in your code base whenever you push a code or open a pull request.
---
name: Linter

on:
  push:
    branches-ignore: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  statuses: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies BE
        run: npm install
        working-directory: ./backend

      - name: Install Dependencies FE
        run: npm install
        working-directory: ./client

      - name: eslint
        run: npm run lint

      - name: prettier
        run: npm run format
