# This workflow executes several linters on changed files based on languages
# used in your code base whenever you push a code or open a pull request.
---
name: Linter

on:
  push:
    branches-ignore: ["main"]
    paths:
      - "backend/**"
      - "client/**"
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  statuses: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v34

      - name: Install Dependencies BE
        if: contains(steps.changed-files.outputs.all_modified_files, 'backend/')
        run: npm install
        working-directory: ./backend

      - name: eslint-be
        if: contains(steps.changed-files.outputs.all_modified_files, 'backend/')
        run: npm run lint
        working-directory: ./backend

      - name: prettier-be
        if: contains(steps.changed-files.outputs.all_modified_files, 'backend/')
        run: npm run format
        working-directory: ./backend

      - name: Install Dependencies FE
        if: contains(steps.changed-files.outputs.all_modified_files, 'client/')
        run: npm install
        working-directory: ./client

      - name: eslint-fe
        if: contains(steps.changed-files.outputs.all_modified_files, 'client/')
        run: npm run lint
        working-directory: ./client

      - name: prettier-fe
        if: contains(steps.changed-files.outputs.all_modified_files, 'client/')
        run: npm run format
        working-directory: ./client